#READS THE CONTENTS OF A FILE
DEF VIEW_CONTENT(FILENAME):
    FILE = OPEN(FILENAME, "R")
    CONTENT = FILE.READ()
    PRINT(CONTENT)
    FILE.CLOSE
DEF WRITE_CONTENT(FILENAME):
    FILE = OPEN(FILENAME, "W")
    CONTENT = FILE.WRITE(FILE_INPUT)
    PRINT("SUCCESSFULLY OVERWITTEN CONTENT OF THE FILE.")
    PRINT(CONTENT)
    FILE.CLOSE()
DEF WRITE_EXTERNALFILE(FILENAME, NEW_FILENAME):
    FOR CONTENT IN FILENAME:
         FILE = OPEN(FILENAME, "R")
         CONTENT = FILE.READ()
         NEW_FILE = OPEN(NEW_FILENAME, "W")
         NEW_FILENAME = NEW_FILE.WRITE(CONTENT)
         PRINT(NEW_FILENAME)

DEF APPEND_CONTENT(FILENAME):
    FILE = OPEN(FILENAME, "A")
    CONTENT = FILE.WRITE(APPEND_INPUT)
    PRINT(CONTENT)
WHILE TRUE:
    USER_INPUT = INPUT("""KINDLY INPUT AN OPERATION TO PERFORM TODAY
                           R TO READ A FILENAME
                           W TO OVERWRITE A FILE
                           A TO APPEND TO A FILE
                           RW TO WRITE TO A NEW FILE
                           Q TO QUIT PROGRAM: """)
    TRY:
       
        IF USER_INPUT == "R":
            FILENAME = INPUT("PLEASE SPECIFY FILE NAME: ")
            TRY:
                VIEW_CONTENT(FILENAME)
                BREAK
            EXCEPT FILENOTFOUNDERROR:
                PRINT("SORRY FILE DOES NOT EXIST....ENTER Q TO QUIT PROGRAM.")
        ELIF USER_INPUT == "W":
            FILENAME = INPUT("PLEASE SPECIFY FILE NAME: ")
            FILE_INPUT = INPUT("TYPE IN CONTENT OF FILE: ")
            TRY:
                WRITE_CONTENT(FILENAME)
                BREAK
            EXCEPT FILENOTFOUNDERROR:
                PRINT("SORRY FILE DOES NOT EXIST....ENTER Q TO QUIT PROGRAM.")
        ELIF USER_INPUT == "RW":
            FILENAME = INPUT("PLEASE SPECIFY FILE NAME: ")
            TRY:
                NEW_FILENAME = INPUT("SET A NAME FOR YOUR NEW FILE: ")
                WRITE_EXTERNALFILE(FILENAME,NEW_FILENAME)
                BREAK
            EXCEPT FILENOTFOUNDERROR:
                PRINT("SORRY FILE DOES NOT EXIST....ENTER Q TO QUIT PROGRAM.")
        ELIF USER_INPUT == "A":
            FILENAME = INPUT("PLEASE SPECIFY FILE NAME: ")
            APPEND_INPUT = INPUT("TYPE CONTENTS TO APPEND TO FILE: ")
            TRY:
                APPEND_CONTENT(FILENAME)
                BREAK
            EXCEPT FILENOTFOUNDERROR:
                 PRINT("SORRY FILE DOES NOT EXIST....ENTER Q TO QUIT PROGRAM.")
        ELIF USER_INPUT == "Q":
            BREAK
        ELSE:
            PRINT("INCORRECT INPUT")
    EXCEPT:
        PRINT("ERROR")












